# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "OWNER"  # Replace with your GitHub username
    # Group all GitHub Actions updates into a single PR
    groups:
      github-actions:
        patterns:
          - "*"

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "OWNER"  # Replace with your GitHub username
    # Security updates only (optional - remove comments to enable all updates)
    # open-pull-requests-limit: 0
    # For production, consider grouping minor/patch updates
    groups:
      python-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Pre-commit hooks
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "pre-commit"
    commit-message:
      prefix: "deps"
    # Only update pre-commit config
    allow:
      - dependency-name: "pre-commit"
