name: provenance-demo
base: core22
version: '0.1.0'
summary: Demo CLI showcasing supply chain security and provenance
description: |
  provenance-demo is a Python CLI application with a production-grade
  secure release pipeline including reproducible builds, SBOM generation,
  and cryptographic signatures.

grade: stable
confinement: strict

apps:
  provenance-demo:
    command: bin/provenance-demo.pyz
    plugs:
      - home
      - network

parts:
  cli:
    plugin: dump
    source: dist/
    organize:
      'provenance-demo.pyz': bin/provenance-demo.pyz
    stage:
      - bin/provenance-demo.pyz
