name: demo-secure-cli
base: core22
version: '0.1.0'
summary: Secure CLI with reproducible releases
description: |
  demo-secure-cli is a Python CLI application with a production-grade
  secure release pipeline including reproducible builds, SBOM generation,
  and cryptographic signatures.

grade: stable
confinement: strict

apps:
  demo:
    command: bin/redoubt-release-template.pyz
    plugs:
      - home
      - network

parts:
  cli:
    plugin: dump
    source: dist/
    organize:
      'redoubt-release-template.pyz': bin/redoubt-release-template.pyz
    stage:
      - bin/redoubt-release-template.pyz
