# WinGet manifest for Provenance Demo
# Submit to: https://github.com/microsoft/winget-pkgs

PackageIdentifier: redoubt-cysec.ProvenanceDemo
PackageVersion: 0.0.1-alpha.7
PackageLocale: en-US
Publisher: redoubt-cysec
PublisherUrl: https://github.com/redoubt-cysec
PublisherSupportUrl: https://github.com/redoubt-cysec/provenance-template/issues
Author: redoubt-cysec
PackageName: Provenance Demo
PackageUrl: https://github.com/redoubt-cysec/provenance-template
License: MIT
LicenseUrl: https://github.com/redoubt-cysec/provenance-template/blob/main/LICENSE
ShortDescription: Demo CLI showcasing supply chain security and provenance
Description: |-
  Provenance Demo demonstrates production-grade supply chain security.

  Features:
  - Reproducible, deterministic builds
  - Sigstore signatures and GitHub attestations
  - SLSA provenance and SBOM generation
  - OSV vulnerability scanning
  - Complete supply chain security validation

  Run 'provenance-demo verify' to validate all security attestations!
Moniker: provenance-demo
Tags:
  - cli
  - security
  - slsa
  - sigstore
  - supply-chain
  - attestation
  - sbom
  - verification
ReleaseNotes: |-
  Initial release of Provenance Demo
  - Self-verification command
  - Complete security attestation chain
  - VM-tested installation across platforms
ReleaseNotesUrl: https://github.com/redoubt-cysec/provenance-template/releases/tag/v0.0.1-alpha.7
Installers:
  - Architecture: x64
    InstallerType: portable
    InstallerUrl: https://github.com/redoubt-cysec/provenance-template/releases/download/v0.0.1-alpha.7/provenance-demo.pyz
    InstallerSha256: 941f327df954fae8bbe2b46395c809a25673e9977c15f986ffbdfd5c5b0c44e7
    Commands:
      - provenance-demo
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Python.Python.3.10
          MinimumVersion: 3.10.0
ManifestType: singleton
ManifestVersion: 1.5.0
