name: Main — Pre-release Security Gates
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f  # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Deterministic env
        run: |
          echo "TZ=UTC" >> $GITHUB_ENV
          echo "LC_ALL=C" >> $GITHUB_ENV
          echo "LANG=C" >> $GITHUB_ENV
          echo "PYTHONHASHSEED=0" >> $GITHUB_ENV
          echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
          umask 0022

      - name: Build sdist+wheel+pyz
        run: |
          ./scripts/build_pyz.sh

      - name: Generate SBOM (CycloneDX)
        run: |
          uv pip install --system cyclonedx-bom
          uv run --no-project python -m cyclonedx_bom -o sbom.cdx.json

      - name: Determinism audit (double-build diff)
        run: |
          sha256sum dist/* > first.sum
          git clean -xdf
          ./scripts/build_pyz.sh
          sha256sum dist/* > second.sum
          diff -u first.sum second.sum

      - name: OSV scan SBOM
        run: |
          curl -sSfL https://github.com/google/osv-scanner/releases/latest/download/osv-scanner_Linux_x86_64.tar.gz \
          | tar xz && sudo mv ./osv-scanner /usr/local/bin/
          osv-scanner --sbom=sbom.cdx.json --format=json > osv-report.json || true

      - name: Upload artifacts
        uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097  # v4.4.3
        with:
          name: main-pre-release-artifacts
          path: |
            dist/*
            sbom.cdx.json
            osv-report.json
