name: PR — Quick Security & Build
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  quick:
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f  # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Dependency Review
        uses: actions/dependency-review-action@4081bf99e2866ebe428fc0477b69eb4fcda7220a  # v4.4.0
        with:
          fail-on-severity: critical

      - name: Install gitleaks
        run: |
          curl -sSfL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_linux_x64.tar.gz \
          | tar xz && sudo mv gitleaks /usr/local/bin/
      - name: Run gitleaks
        run: gitleaks detect --source . --no-git --redact

      - name: CodeQL init
        uses: github/codeql-action/init@662472033e021d55d94146f66f6058822b0b39fd  # v3.27.0
        with:
          languages: python
      - name: CodeQL analyze
        uses: github/codeql-action/analyze@662472033e021d55d94146f66f6058822b0b39fd  # v3.27.0

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
        with:
          python-version: '3.11'

      - name: Sanity build
        run: |
          ./scripts/build_pyz.sh
