name: Secure Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Secure release workflow triggered for tag: ${{ github.ref_name }}"
          echo "This is a minimal test to verify the workflow triggers"
