name: Secure Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Create test file
        run: |
          mkdir -p dist
          echo "test" > dist/test.txt

      - name: Upload artifacts for Chocolatey job
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
        with:
          name: pyz-artifact
          path: dist/test.txt
          retention-days: 1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191  # v2.0.8
        with:
          files: dist/*
          body: "Test release with Chocolatey job"

  chocolatey:
    needs: release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Download artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093  # v4.3.0
        with:
          name: pyz-artifact
          path: dist

      - name: Test Chocolatey job
        shell: powershell
        run: |
          Write-Host "Chocolatey job triggered successfully!"
          Get-ChildItem dist
