name: Export Snapcraft Credentials (One-Time Setup)

on:
  workflow_dispatch:
    inputs:
      use_macaroon:
        description: 'Use macaroon from dashboard.snapcraft.io (recommended)'
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  get-credentials:
    name: Get Snapcraft Credentials via Web
    runs-on: ubuntu-latest

    steps:
      - name: Instructions for Web-Based Export
        run: |
          echo "================================================"
          echo "GET SNAPCRAFT CREDENTIALS (Web Method)"
          echo "================================================"
          echo ""
          echo "Since you've already logged into Snapcraft.io:"
          echo ""
          echo "Method 1: Export from Dashboard (EASIEST)"
          echo "  1. Go to: https://dashboard.snapcraft.io/account/"
          echo "  2. Scroll down to 'Account Information'"
          echo "  3. Look for 'Macaroon' or 'Export Login' button"
          echo "  4. Click it and download/copy the credentials"
          echo "  5. Add to GitHub:"
          echo ""
          echo "     gh secret set SNAPCRAFT_STORE_CREDENTIALS \\"
          echo "       --repo ${{ github.repository }} \\"
          echo "       --body \"PASTE_CREDENTIALS_HERE\""
          echo ""
          echo "================================================"
          echo ""
          echo "Method 2: Use Snapcraft CLI with Keyring Fix"
          echo ""
          echo "  On a Linux machine/VM:"
          echo ""
          echo "  # Fix keyring issue"
          echo "  sudo apt update"
          echo "  sudo apt install -y gnome-keyring dbus-x11"
          echo "  eval \$(dbus-launch --sh-syntax)"
          echo "  eval \$(echo \"\" | gnome-keyring-daemon --unlock)"
          echo ""
          echo "  # Now login and export"
          echo "  snapcraft login"
          echo "  snapcraft export-login snapcraft-creds.txt"
          echo "  cat snapcraft-creds.txt"
          echo ""
          echo "================================================"
          echo ""
          echo "Method 3: Use Multipass on macOS (with keyring)"
          echo ""
          echo "  multipass launch --name snapcred 22.04"
          echo "  multipass shell snapcred"
          echo ""
          echo "  # Inside VM:"
          echo "  sudo apt update"
          echo "  sudo apt install -y snapcraft gnome-keyring dbus-x11"
          echo "  eval \$(dbus-launch --sh-syntax)"
          echo "  eval \$(echo \"\" | gnome-keyring-daemon --unlock)"
          echo "  snapcraft login"
          echo "  snapcraft export-login snapcraft-credentials.txt"
          echo "  cat snapcraft-credentials.txt"
          echo ""
          echo "  # Exit and transfer"
          echo "  exit"
          echo "  multipass transfer snapcred:snapcraft-credentials.txt ."
          echo "  gh secret set SNAPCRAFT_STORE_CREDENTIALS < snapcraft-credentials.txt"
          echo "  rm snapcraft-credentials.txt"
          echo "  multipass delete snapcred && multipass purge"
          echo ""
          echo "================================================"

  export-with-keyring:
    name: Instructions
        run: |
          echo "================================================"
          echo "SNAPCRAFT CREDENTIAL EXPORT HELPER"
          echo "================================================"
          echo ""
          echo "This workflow will help you export credentials."
          echo "However, snapcraft login requires interactive browser auth."
          echo ""
          echo "Please run these commands on a Linux machine or VM:"
          echo ""
          echo "  1. Install snapcraft:"
          echo "     sudo snap install snapcraft --classic"
          echo ""
          echo "  2. Login:"
          echo "     snapcraft login"
          echo "     (Use email: ${{ github.event.inputs.snapcraft_email }})"
          echo ""
          echo "  3. Export credentials:"
          echo "     snapcraft export-login snapcraft-credentials.txt"
          echo ""
          echo "  4. View credentials:"
          echo "     cat snapcraft-credentials.txt"
          echo ""
          echo "  5. Add to GitHub Secrets:"
          echo "     gh secret set SNAPCRAFT_STORE_CREDENTIALS \\"
          echo "       --repo ${{ github.repository }} \\"
          echo "       --body \"\$(cat snapcraft-credentials.txt)\""
          echo ""
          echo "  6. Clean up:"
          echo "     rm snapcraft-credentials.txt"
          echo ""
          echo "================================================"
          echo ""
          echo "Alternative: Use Multipass on macOS:"
          echo ""
          echo "  brew install multipass"
          echo "  multipass launch --name snap-export 22.04"
          echo "  multipass shell snap-export"
          echo "  sudo snap install snapcraft --classic"
          echo "  snapcraft login"
          echo "  snapcraft export-login snapcraft-credentials.txt"
          echo "  cat snapcraft-credentials.txt"
          echo "  exit"
          echo "  multipass transfer snap-export:snapcraft-credentials.txt ."
          echo "  gh secret set SNAPCRAFT_STORE_CREDENTIALS < snapcraft-credentials.txt"
          echo "  rm snapcraft-credentials.txt"
          echo "  multipass delete snap-export && multipass purge"
          echo ""
          echo "================================================"
