name: Test Tag Trigger

on:
  push:
    tags: ['v*']

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Tag trigger works! Tag: ${{ github.ref_name }}"
