name: Test Minimal Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Minimal release workflow triggered for tag: ${{ github.ref_name }}"
