name: windows-testing
on: [workflow_dispatch, pull_request]

permissions:
  contents: read  # Only needs to checkout code for testing

jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        package_manager: [winget]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Prep Scoop bucket (local)
        if: matrix.package_manager == 'scoop'
        shell: powershell
        run: |
          iwr -useb get.scoop.sh | iex
          scoop bucket add owner "${{ github.workspace }}\packaging\scoop"

      - name: Test ${{ matrix.package_manager }}
        shell: powershell
        run: |
          switch ("${{ matrix.package_manager }}") {
            "scoop" {
              scoop install provenance-demo
              provenance-demo --version
            }
            "chocolatey" {
              choco install chocolatey.server -y
              Start-Service chocolatey.server -ErrorAction SilentlyContinue
              # TODO: choco push your .nupkg to http://localhost:8080/ and install:
              # choco push .\dist\provenance-demo*.nupkg --source http://localhost:8080/
              # choco install provenance-demo -y --source http://localhost:8080/
            }
            "winget" {
              # Enable local manifest support so winget can install from a file
              winget source remove --name msstore
              winget settings --enable LocalManifestFiles
              winget validate .\packaging\winget\manifests\OWNER.redoubt.yaml
              winget install --manifest .\packaging\winget\manifests\OWNER.redoubt.yaml `
                --silent --accept-source-agreements --accept-package-agreements
              $linkDir = Join-Path $Env:LOCALAPPDATA 'Microsoft\WinGet\Links'
              if (Test-Path $linkDir) {
                $Env:PATH = "$linkDir;$Env:PATH"
                Get-ChildItem $linkDir
              }
              provenance-demo --version
            }
          }
